drop index idx2twt1 ;
drop index idx2twt2 ;
drop index idx3twt1 ;
drop index idx3twt2 ;
drop index idx3twt3 ;
drop index idxbat ;
drop index idxbusbar ;
drop index idxconfbus;
drop index idxdang ;
drop index idxgen ;
drop index idxlcc ;
drop index idxline1 ;
drop index idxline2 ;
drop index idxload ;
drop index idxshunt ;
drop index idxstatic ;
drop index idxswi ;
drop index idxvl ;
drop index idxvsc ;
DROP TABLE battery ;
DROP TABLE busbarSection;
DROP TABLE configuredBus;
DROP TABLE danglingLine ;
DROP TABLE generator ;
DROP TABLE hvdcLine ;
DROP TABLE lccConverterStation ;
DROP TABLE line ;
DROP TABLE load ;
DROP TABLE network ;
DROP TABLE shuntCompensator ;
DROP TABLE staticVarCompensator ;
DROP TABLE substation;
DROP TABLE switch ;
DROP TABLE threeWindingsTransformer ;
DROP TABLE twoWindingsTransformer ;
DROP TABLE voltageLevel ;
DROP TABLE vscConverterStation;
