CREATE TABLE network (
    uuid RAW(16),
    variantNum int,
    id varchar2(100),
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    idByAlias clob,
    caseDate timestamp,
    forecastDistance int,
    sourceFormat varchar(100),
    connectedComponentsValid NUMBER(1),
    synchronousComponentsValid NUMBER(1),
    cgmesSvMetadata clob,
    cgmesSshMetadata clob,
    cimCharacteristics clob,
    cgmesControlAreas clob,
    cgmesIidmMapping clob,
    variantId varchar(100),
    PRIMARY KEY (uuid, variantNum)
);

CREATE TABLE substation (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    country clob,
    tso clob,
    entsoeArea clob,
    geographicalTags clob,
    PRIMARY KEY (networkUuid, variantNum, id)
);

CREATE TABLE voltageLevel (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    substationId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    nominalV double precision,
    lowVoltageLimit double precision,
    highVoltageLimit double precision,
    topologyKind clob,
    internalConnections clob,
    calculatedBusesForBusView clob,
    nodeToCalculatedBusForBusView clob,
    busToCalculatedBusForBusView clob,
    calculatedBusesForBusBreakerView clob,
    nodeToCalculatedBusForBusBreakerView clob,
    busToCalculatedBusForBusBreakerView clob,
    calculatedBusesValid NUMBER(1),
    slackTerminal clob,
    PRIMARY KEY (networkUuid, variantNum, id, substationId)
);

CREATE TABLE generator (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    energySource clob,
    minP double precision,
    maxP double precision,
    voltageRegulatorOn NUMBER(1),
    targetP double precision,
    targetQ double precision,
    targetV double precision,
    ratedS double precision,
    p double precision,
    q double precision,
    position clob,
    minMaxReactiveLimits clob,
    reactiveCapabilityCurve clob,
    bus clob,
    connectableBus clob,
    activePowerControl clob,
    regulatingTerminal clob,
    coordinatedReactiveControl clob,
    remoteReactivePowerControl clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE battery (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    minP double precision,
    maxP double precision,
    p0 double precision,
    q0 double precision,
    p double precision,
    q double precision,
    position clob,
    minMaxReactiveLimits clob,
    reactiveCapabilityCurve clob,
    bus clob,
    connectableBus clob,
    activePowerControl clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE load (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    loadType clob,
    p0 double precision,
    q0 double precision,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    loadDetail clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE shuntCompensator (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    linearModel clob,
    nonLinearModel clob,
    sectionCount int,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    regulatingTerminal clob,
    voltageRegulatorOn NUMBER(1),
    targetV double precision,
    targetDeadband double precision,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE vscConverterStation (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    lossFactor float,
    voltageRegulatorOn NUMBER(1),
    reactivePowerSetPoint double precision,
    voltageSetPoint double precision,
    minMaxReactiveLimits clob,
    reactiveCapabilityCurve clob,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE lccConverterStation (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    powerFactor float,
    lossFactor float,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE staticVarCompensator (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    bMin double precision,
    bMax double precision,
    voltageSetPoint double precision,
    reactivePowerSetPoint double precision,
    regulationMode clob,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    regulatingTerminal clob,
    voltagePerReactivePowerControl clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE busbarSection (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    position clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE switch (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    kind clob,
    node1 int,
    node2 int,
    open NUMBER(1),
    retained NUMBER(1),
    fictitious NUMBER(1),
    bus1 clob,
    bus2 clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE twoWindingsTransformer (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId1 varchar2(100),
    voltageLevelId2 varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node1 int,
    node2 int,
    r double precision,
    x double precision,
    g double precision,
    b double precision,
    ratedU1 double precision,
    ratedU2 double precision,
    ratedS double precision,
    p1 double precision,
    q1 double precision,
    p2 double precision,
    q2 double precision,
    position1 clob,
    position2 clob,
    phaseTapChanger clob,
    ratioTapChanger clob,
    bus1 clob,
    bus2 clob,
    connectableBus1 clob,
    connectableBus2 clob,
    currentLimits1 clob,
    currentLimits2 clob,
    activePowerLimits1 clob,
    activePowerLimits2 clob,
    apparentPowerLimits1 clob,
    apparentPowerLimits2 clob,
    phaseAngleClock clob,
    branchStatus clob,
    PRIMARY KEY (networkUuid, variantNum, id)
);

CREATE TABLE threeWindingsTransformer (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId1 varchar2(100),
    voltageLevelId2 varchar2(100),
    voltageLevelId3 varchar2(100),
    node1 int,
    node2 int,
    node3 int,
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    ratedU0 double precision,
    p1 double precision,
    q1 double precision,
    r1 double precision,
    x1 double precision,
    g1 double precision,
    b1 double precision,
    ratedU1 double precision,
    ratedS1 double precision,
    phaseTapChanger1 clob,
    ratioTapChanger1 clob,
    p2 double precision,
    q2 double precision,
    r2 double precision,
    x2 double precision,
    g2 double precision,
    b2 double precision,
    ratedU2 double precision,
    ratedS2 double precision,
    phaseTapChanger2 clob,
    ratioTapChanger2 clob,
    p3 double precision,
    q3 double precision,
    r3 double precision,
    x3 double precision,
    g3 double precision,
    b3 double precision,
    ratedU3 double precision,
    ratedS3 double precision,
    phaseTapChanger3 clob,
    ratioTapChanger3 clob,
    position1 clob,
    position2 clob,
    position3 clob,
    currentLimits1 clob,
    currentLimits2 clob,
    currentLimits3 clob,
    activePowerLimits1 clob,
    activePowerLimits2 clob,
    activePowerLimits3 clob,
    apparentPowerLimits1 clob,
    apparentPowerLimits2 clob,
    apparentPowerLimits3 clob,
    bus1 clob,
    connectableBus1 clob,
    bus2 clob,
    connectableBus2 clob,
    bus3 clob,
    connectableBus3 clob,
    phaseAngleClock clob,
    branchStatus clob,
    PRIMARY KEY (networkUuid, variantNum, id)
);

CREATE TABLE line (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId1 varchar2(100),
    voltageLevelId2 varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node1 int,
    node2 int,
    r double precision,
    x double precision,
    g1 double precision,
    b1 double precision,
    g2 double precision,
    b2 double precision,
    p1 double precision,
    q1 double precision,
    p2 double precision,
    q2 double precision,
    position1 clob,
    position2 clob,
    bus1 clob,
    bus2 clob,
    connectableBus1 clob,
    connectableBus2 clob,
    mergedXnode clob,
    currentLimits1 clob,
    currentLimits2 clob,
    activePowerLimits1 clob,
    activePowerLimits2 clob,
    apparentPowerLimits1 clob,
    apparentPowerLimits2 clob,
    branchStatus clob,
    PRIMARY KEY (networkUuid, variantNum, id)
);

CREATE TABLE hvdcLine (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    r double precision,
    convertersMode clob,
    nominalV double precision,
    activePowerSetpoint double precision,
    maxP double precision,
    converterStationId1 clob,
    converterStationId2 clob,
    hvdcAngleDroopActivePowerControl clob,
    hvdcOperatorActivePowerRange clob,
    PRIMARY KEY (networkUuid, variantNum, id)
);

CREATE TABLE danglingLine (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    node int,
    p0 double precision,
    q0 double precision,
    r double precision,
    x double precision,
    g double precision,
    b double precision,
    generation clob,
    ucteXNodeCode clob,
    currentLimits clob,
    activePowerLimits clob,
    apparentPowerLimits clob,
    p double precision,
    q double precision,
    position clob,
    bus clob,
    connectableBus clob,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

CREATE TABLE configuredBus (
    networkUuid RAW(16),
    variantNum int,
    id varchar2(100),
    voltageLevelId varchar2(100),
    name clob,
    fictitious NUMBER(1),
    properties clob,
    aliasesWithoutType clob,
    aliasByType clob,
    v double precision,
    angle double precision,
    PRIMARY KEY (networkUuid, variantNum, id, voltageLevelId)
);

create index idxvl on voltageLevel (networkUuid, variantNum, substationId);
create index idxgen on generator (networkUuid, variantNum, voltageLevelId);
create index idxbat on battery (networkUuid, variantNum, voltageLevelId);
create index idxload on load (networkUuid, variantNum, voltageLevelId);
create index idxshunt on shuntCompensator (networkUuid, variantNum, voltageLevelId);
create index idxvsc on vscConverterStation (networkUuid, variantNum, voltageLevelId);
create index idxlcc on lccConverterStation (networkUuid, variantNum, voltageLevelId);
create index idxstatic on staticVarCompensator (networkUuid, variantNum, voltageLevelId);
create index idxbusbar on busbarSection (networkUuid, variantNum, voltageLevelId);
create index idxswi on switch (networkUuid, variantNum, voltageLevelId);
create index idx2twt1 on twoWindingsTransformer (networkUuid, variantNum, voltageLevelId1);
create index idx2twt2 on twoWindingsTransformer (networkUuid, variantNum, voltageLevelId2);
create index idx3twt1 on threeWindingsTransformer (networkUuid, variantNum, voltageLevelId1);
create index idx3twt2 on threeWindingsTransformer (networkUuid, variantNum, voltageLevelId2);
create index idx3twt3 on threeWindingsTransformer (networkUuid, variantNum, voltageLevelId3);
create index idxline1 on line (networkUuid, variantNum, voltageLevelId1);
create index idxline2 on line (networkUuid, variantNum, voltageLevelId2);
create index idxdang on danglingLine (networkUuid, variantNum, voltageLevelId);
create index idxconfbus on configuredBus (networkUuid, variantNum, voltageLevelId);
