TRUNCATE iidm.network;

TRUNCATE iidm.substation;

TRUNCATE iidm.generator;

TRUNCATE iidm.load;

TRUNCATE iidm.shuntCompensator;

TRUNCATE iidm.vscConverterStation;

TRUNCATE iidm.lccConverterStation;

TRUNCATE iidm.staticVarCompensator;

TRUNCATE iidm.busbarSection;

TRUNCATE iidm.switch;

TRUNCATE iidm.twoWindingsTransformer;

TRUNCATE iidm.threeWindingsTransformer;

TRUNCATE iidm.line;

TRUNCATE iidm.hvdcLine;

TRUNCATE iidm.danglingLine;

TRUNCATE iidm.configuredBus;
