package com.powsybl.network.store.iidm.impl.tck.voltage.regulation.backward.compatibility;

import com.powsybl.iidm.network.tck.voltage.regulation.backward.compatibility.AbstractVoltageRegulationBackwardCompatibilityOnVscConverterStationTest;

class VoltageRegulationBackwardCompatibilityOnVscConverterStationTest extends AbstractVoltageRegulationBackwardCompatibilityOnVscConverterStationTest {
}
