package com.powsybl.network.store.iidm.impl.tck.voltage.regulation.backward.compatibility;

import com.powsybl.iidm.network.tck.voltage.regulation.backward.compatibility.AbstractVoltageRegulationBackwardCompatibilityOnBatteryTest;

class VoltageRegulationBackwardCompatibilityOnBatteryTest extends AbstractVoltageRegulationBackwardCompatibilityOnBatteryTest {
}
