package com.powsybl.network.store.iidm.impl.tck.voltage.regulation.backward.compatibility;

import com.powsybl.iidm.network.tck.voltage.regulation.backward.compatibility.AbstractVoltageRegulationBackwardCompatibilityOnStaticVarCompensatorTest;

class VoltageRegulationBackwardCompatibilityOnStaticVarCompensatorTest extends AbstractVoltageRegulationBackwardCompatibilityOnStaticVarCompensatorTest {
}
